#spring.application.name=auth-service
server:
  port: 9000
#logging:
#  level:
#    root: INFO
#    org.springframework.security: TRACE
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true