#spring.application.name=auth-service
server:
  port: 9000
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: duongbach20231@gmail.com
    password: elxuzbqqgkrwzjor
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true